<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currencies = [
            ['id' => '1', 'name' => 'US Dollar', 'code' => 'USD', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '2', 'name' => 'Albanian Lek', 'code' => 'ALL', 'symbol' => 'Lek', 'paypal_supported' => '0', 'stripe_supported' => '1', 'flutterwave_supported' => '0'],
            ['id' => '3', 'name' => 'Algerian Dinar', 'code' => 'DZD', 'symbol' => 'د.ج', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '4', 'name' => 'Andorran Franc', 'code' => 'ADF', 'symbol' => 'Franc', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '5', 'name' => 'Angolan Kwanza', 'code' => 'AOA', 'symbol' => 'Kz', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '6', 'name' => 'Argentine Peso', 'code' => 'ARS', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '7', 'name' => 'Armenian Dram', 'code' => 'AMD', 'symbol' => 'դր.', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '8', 'name' => 'Aruban Florin', 'code' => 'AWG', 'symbol' => 'ƒ', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '9', 'name' => 'Australian Dollar', 'code' => 'AUD', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '10', 'name' => 'Azerbaijani Manat', 'code' => 'AZN', 'symbol' => '₼', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '11', 'name' => 'Bahamas Dollar', 'code' => 'BSD', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '12', 'name' => 'Bahraini Dinar', 'code' => 'BHD', 'symbol' => '.د.ب', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '13', 'name' => 'Bangladeshi Taka', 'code' => 'BDT', 'symbol' => '৳', 'paypal_supported' => '0', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '14', 'name' => 'Barbadian Dollar', 'code' => 'BBD', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '0'],
            ['id' => '15', 'name' => 'Belarusian Ruble', 'code' => 'BYN', 'symbol' => 'Br', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '16', 'name' => 'Belgian Franc', 'code' => 'BEF', 'symbol' => 'Fr', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '17', 'name' => 'Belize Dollar', 'code' => 'BZD', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '0'],
            ['id' => '18', 'name' => 'Bermudian Dollar', 'code' => 'BMD', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '0'],
            ['id' => '19', 'name' => 'Bhutanese Ngultrum', 'code' => 'BTN', 'symbol' => 'Nu.', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '20', 'name' => 'Bolivian Boliviano', 'code' => 'BOB', 'symbol' => 'Bs.', 'paypal_supported' => '0', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '21', 'name' => 'Bosnia and Herzegovina Convertible Mark', 'code' => 'BAM', 'symbol' => 'KM', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '22', 'name' => 'Botswana Pula', 'code' => 'BWP', 'symbol' => 'P', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '23', 'name' => 'Brazilian Real', 'code' => 'BRL', 'symbol' => 'R$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '24', 'name' => 'British Pound Sterling', 'code' => 'GBP', 'symbol' => '£', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '25', 'name' => 'Brunei Dollar', 'code' => 'BND', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '0'],
            ['id' => '26', 'name' => 'Bulgarian Lev', 'code' => 'BGN', 'symbol' => 'лв.', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '27', 'name' => 'Burundian Franc', 'code' => 'BIF', 'symbol' => 'Fr', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '28', 'name' => 'Cambodian Riel', 'code' => 'KHR', 'symbol' => '៛', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '29', 'name' => 'Canadian Dollar', 'code' => 'CAD', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '30', 'name' => 'Cape Verdean Escudo', 'code' => 'CVE', 'symbol' => '$', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '31', 'name' => 'Cayman Islands Dollar', 'code' => 'KYD', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '0'],
            ['id' => '32', 'name' => 'Central African CFA Franc', 'code' => 'XAF', 'symbol' => 'Fr', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '33', 'name' => 'Chilean Peso', 'code' => 'CLP', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '34', 'name' => 'Chinese Yuan', 'code' => 'CNY', 'symbol' => '¥', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '35', 'name' => 'Colombian Peso', 'code' => 'COP', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '36', 'name' => 'Comorian Franc', 'code' => 'KMF', 'symbol' => 'Fr', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '37', 'name' => 'Congolese Franc', 'code' => 'CDF', 'symbol' => 'Fr', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '38', 'name' => 'Costa Rican Colón', 'code' => 'CRC', 'symbol' => '₡', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '39', 'name' => 'Croatian Kuna', 'code' => 'HRK', 'symbol' => 'kn', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '0'],
            ['id' => '40', 'name' => 'Cuban Peso', 'code' => 'CUP', 'symbol' => '$', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '41', 'name' => 'Czech Koruna', 'code' => 'CZK', 'symbol' => 'Kč', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '0'],
            ['id' => '42', 'name' => 'Danish Krone', 'code' => 'DKK', 'symbol' => 'kr', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '43', 'name' => 'Djiboutian Franc', 'code' => 'DJF', 'symbol' => 'Fr', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '44', 'name' => 'Dominican Peso', 'code' => 'DOP', 'symbol' => 'RD$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '45', 'name' => 'Egyptian Pound', 'code' => 'EGP', 'symbol' => '£', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '46', 'name' => 'Equatorial Guinean Franc', 'code' => 'XAF', 'symbol' => 'Fr', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '47', 'name' => 'Eritrean Nakfa', 'code' => 'ERN', 'symbol' => 'Nkf', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '48', 'name' => 'Estonian Kroon', 'code' => 'EEK', 'symbol' => 'kr', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '49', 'name' => 'Ethiopian Birr', 'code' => 'ETB', 'symbol' => 'Br', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '50', 'name' => 'Euro', 'code' => 'EUR', 'symbol' => '€', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '51', 'name' => 'Fijian Dollar', 'code' => 'FJD', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '0'],
            ['id' => '52', 'name' => 'Gambian Dalasi', 'code' => 'GMD', 'symbol' => 'D', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '53', 'name' => 'Georgian Lari', 'code' => 'GEL', 'symbol' => '₾', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '54', 'name' => 'Ghanaian Cedi', 'code' => 'GHS', 'symbol' => '₵', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '55', 'name' => 'Gibraltar Pound', 'code' => 'GIP', 'symbol' => '£', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '0'],
            ['id' => '56', 'name' => 'Guatemalan Quetzal', 'code' => 'GTQ', 'symbol' => 'Q', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '57', 'name' => 'Guinean Franc', 'code' => 'GNF', 'symbol' => 'Fr', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '58', 'name' => 'Guyanese Dollar', 'code' => 'GYD', 'symbol' => '$', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '59', 'name' => 'Haitian Gourde', 'code' => 'HTG', 'symbol' => 'G', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '60', 'name' => 'Honduran Lempira', 'code' => 'HNL', 'symbol' => 'L', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '0'],
            ['id' => '61', 'name' => 'Hungarian Forint', 'code' => 'HUF', 'symbol' => 'Ft', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '0'],
            ['id' => '62', 'name' => 'Icelandic Króna', 'code' => 'ISK', 'symbol' => 'kr', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '63', 'name' => 'Indian Rupee', 'code' => 'INR', 'symbol' => '₹', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '64', 'name' => 'Indonesian Rupiah', 'code' => 'IDR', 'symbol' => 'Rp', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '65', 'name' => 'Iranian Rial', 'code' => 'IRR', 'symbol' => '﷼', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '66', 'name' => 'Iraqi Dinar', 'code' => 'IQD', 'symbol' => 'ع.د', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '67', 'name' => 'Israeli New Shekel', 'code' => 'ILS', 'symbol' => '₪', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '68', 'name' => 'Italian Lira', 'code' => 'ITL', 'symbol' => '₤', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '69', 'name' => 'Jamaican Dollar', 'code' => 'JMD', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '0'],
            ['id' => '70', 'name' => 'Japanese Yen', 'code' => 'JPY', 'symbol' => '¥', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '71', 'name' => 'Jordanian Dinar', 'code' => 'JOD', 'symbol' => 'د.ا', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '72', 'name' => 'Kazakhstani Tenge', 'code' => 'KZT', 'symbol' => '₸', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '73', 'name' => 'Kenyan Shilling', 'code' => 'KES', 'symbol' => 'KSh', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '74', 'name' => 'Kuwaiti Dinar', 'code' => 'KWD', 'symbol' => 'د.ك', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '75', 'name' => 'Kyrgystani Som', 'code' => 'KGS', 'symbol' => 'с', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '76', 'name' => 'Laotian Kip', 'code' => 'LAK', 'symbol' => '₭', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '77', 'name' => 'Latvian Lats', 'code' => 'LVL', 'symbol' => 'Ls', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '78', 'name' => 'Lebanese Pound', 'code' => 'LBP', 'symbol' => 'ل.ل', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '79', 'name' => 'Liberian Dollar', 'code' => 'LRD', 'symbol' => '$', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '80', 'name' => 'Libyan Dinar', 'code' => 'LYD', 'symbol' => 'ل.د', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '81', 'name' => 'Lithuanian Litas', 'code' => 'LTL', 'symbol' => 'Lt', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '82', 'name' => 'Luxembourgian Franc', 'code' => 'LUF', 'symbol' => '₣', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '83', 'name' => 'Malagasy Ariary', 'code' => 'MGA', 'symbol' => 'Ar', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '84', 'name' => 'Malawian Kwacha', 'code' => 'MWK', 'symbol' => 'MK', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '85', 'name' => 'Malaysian Ringgit', 'code' => 'MYR', 'symbol' => 'RM', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '86', 'name' => 'Mauritanian Ouguiya', 'code' => 'MRU', 'symbol' => 'UM', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '87', 'name' => 'Mauritian Rupee', 'code' => 'MUR', 'symbol' => 'Rs', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '88', 'name' => 'Mexican Peso', 'code' => 'MXN', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '89', 'name' => 'Moldovan Leu', 'code' => 'MDL', 'symbol' => 'L', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '90', 'name' => 'Mongolian Tugrik', 'code' => 'MNT', 'symbol' => '₮', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '91', 'name' => 'Moroccan Dirham', 'code' => 'MAD', 'symbol' => 'د.م.', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '92', 'name' => 'Mozambican Metical', 'code' => 'MZN', 'symbol' => 'MT', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '93', 'name' => 'Myanmar Kyat', 'code' => 'MMK', 'symbol' => 'K', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '94', 'name' => 'Namibian Dollar', 'code' => 'NAD', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '0'],
            ['id' => '95', 'name' => 'Nauruan Dollar', 'code' => 'AUD', 'symbol' => '$', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '96', 'name' => 'Nepalese Rupee', 'code' => 'NPR', 'symbol' => 'Rs', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '97', 'name' => 'Netherlands Antillean Guilder', 'code' => 'ANG', 'symbol' => 'ƒ', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '98', 'name' => 'New Zealand Dollar', 'code' => 'NZD', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '99', 'name' => 'Nigerian Naira', 'code' => 'NGN', 'symbol' => '₦', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '100', 'name' => 'North Korean Won', 'code' => 'KPW', 'symbol' => '₩', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '101', 'name' => 'Norwegian Krone', 'code' => 'NOK', 'symbol' => 'kr', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '102', 'name' => 'Omani Rial', 'code' => 'OMR', 'symbol' => 'ر.ع.', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '103', 'name' => 'Pakistani Rupee', 'code' => 'PKR', 'symbol' => 'Rs', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '104', 'name' => 'Papua New Guinean Kina', 'code' => 'PGK', 'symbol' => 'K', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '105', 'name' => 'Paraguayan Guarani', 'code' => 'PYG', 'symbol' => '₲', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '106', 'name' => 'Peruvian Nuevo Sol', 'code' => 'PEN', 'symbol' => 'S/.', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '107', 'name' => 'Philippine Peso', 'code' => 'PHP', 'symbol' => '₱', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '108', 'name' => 'Polish Zloty', 'code' => 'PLN', 'symbol' => 'zł', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '0'],
            ['id' => '109', 'name' => 'Qatari Rial', 'code' => 'QAR', 'symbol' => 'ر.ق', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '110', 'name' => 'Romanian Leu', 'code' => 'RON', 'symbol' => 'lei', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '111', 'name' => 'Russian Ruble', 'code' => 'RUB', 'symbol' => '₽', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '112', 'name' => 'Rwandan Franc', 'code' => 'RWF', 'symbol' => 'Fr', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '113', 'name' => 'Saint Helena Pound', 'code' => 'SHP', 'symbol' => '£', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '114', 'name' => 'Samoan Tala', 'code' => 'WST', 'symbol' => 'T', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '115', 'name' => 'Sao Tome and Principe Dobra', 'code' => 'STN', 'symbol' => 'Db', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '116', 'name' => 'Saudi Riyal', 'code' => 'SAR', 'symbol' => 'ر.س', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '117', 'name' => 'Serbian Dinar', 'code' => 'RSD', 'symbol' => 'Дин.', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '0'],
            ['id' => '118', 'name' => 'Seychellois Rupee', 'code' => 'SCR', 'symbol' => 'Rs', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '119', 'name' => 'Sierra Leonean Leone', 'code' => 'SLL', 'symbol' => 'Le', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '120', 'name' => 'Singapore Dollar', 'code' => 'SGD', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '121', 'name' => 'Solomon Islands Dollar', 'code' => 'SBD', 'symbol' => '$', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '122', 'name' => 'Somali Shilling', 'code' => 'SOS', 'symbol' => 'Sh', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '123', 'name' => 'South African Rand', 'code' => 'ZAR', 'symbol' => 'R', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '124', 'name' => 'South Sudanese Pound', 'code' => 'SSP', 'symbol' => '£', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '125', 'name' => 'Sri Lankan Rupee', 'code' => 'LKR', 'symbol' => 'Rs', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '126', 'name' => 'Sudanese Pound', 'code' => 'SDG', 'symbol' => 'ج.س.', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '127', 'name' => 'Surinamese Dollar', 'code' => 'SRD', 'symbol' => '$', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '128', 'name' => 'Swedish Krona', 'code' => 'SEK', 'symbol' => 'kr', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '129', 'name' => 'Swiss Franc', 'code' => 'CHF', 'symbol' => 'CHF', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '130', 'name' => 'Syrian Pound', 'code' => 'SYP', 'symbol' => 'ل.س', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '131', 'name' => 'Tajikistani Somoni', 'code' => 'TJS', 'symbol' => 'SM', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '132', 'name' => 'Tanzanian Shilling', 'code' => 'TZS', 'symbol' => 'TSh', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '133', 'name' => 'Thai Baht', 'code' => 'THB', 'symbol' => '฿', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '134', 'name' => 'Tongan Paanga', 'code' => 'TOP', 'symbol' => 'T$', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '135', 'name' => 'Trinidad and Tobago Dollar', 'code' => 'TTD', 'symbol' => '$', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '136', 'name' => 'Turkish Lira', 'code' => 'TRY', 'symbol' => '₺', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '137', 'name' => 'Turkmenistani Manat', 'code' => 'TMT', 'symbol' => 'T', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '138', 'name' => 'Ugandan Shilling', 'code' => 'UGX', 'symbol' => 'USh', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '139', 'name' => 'Ukrainian Hryvnia', 'code' => 'UAH', 'symbol' => '₴', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '140', 'name' => 'United Arab Emirates Dirham', 'code' => 'AED', 'symbol' => 'د.إ', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '141', 'name' => 'United States Dollar', 'code' => 'USD', 'symbol' => '$', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '142', 'name' => 'Uruguayan Peso', 'code' => 'UYU', 'symbol' => '$', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '143', 'name' => 'Uzbekistani Som', 'code' => 'UZS', 'symbol' => 'лв', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '144', 'name' => 'Vanuatu Vatu', 'code' => 'VUV', 'symbol' => 'Vt', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '145', 'name' => 'Venezuelan Bolívar', 'code' => 'VES', 'symbol' => 'Bs.S', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '146', 'name' => 'Vietnamese Dong', 'code' => 'VND', 'symbol' => '₫', 'paypal_supported' => '1', 'stripe_supported' => '1', 'flutterwave_supported' => '1'],
            ['id' => '147', 'name' => 'Yemeni Rial', 'code' => 'YER', 'symbol' => 'ر.ي', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '148', 'name' => 'Zambian Kwacha', 'code' => 'ZMW', 'symbol' => 'ZK', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
            ['id' => '149', 'name' => 'Zimbabwean Dollar', 'code' => 'ZWL', 'symbol' => 'Z$', 'paypal_supported' => '0', 'stripe_supported' => '0', 'flutterwave_supported' => '0'],
        ];


        foreach ($currencies as $key => $value) {
            Currency::create($value);
        }
    }
}
